steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - ex4
      - --region=us-central1
      - --source=.
      - --trigger-topic=my-topic
      - --runtime=java17
      - --entry-point com.GcpExercies.GcpExercies.Ex4.PubSubStorageFunction