steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - function-http
      - --region=europe-west4
      - --source=.
      - --trigger-http
      - --runtime=RUNTIME